name: FIPEAPI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/AOM.FIPE.API/**'
      - 'src/AOM.FIPE.API.Tests/**'
      - '.github/workflows/fipe-api.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/AOM.FIPE.API/**'
      - 'src/AOM.FIPE.API.Tests/**'
      - '.github/workflows/fipe-api.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        dotnet restore src/AOM.FIPE.API/AOM.FIPE.API.csproj
        dotnet restore src/AOM.FIPE.API.Tests/AOM.FIPE.API.Tests.csproj
    
    - name: Build
      run: |
        dotnet build --no-restore src/AOM.FIPE.API/AOM.FIPE.API.csproj
        dotnet build --no-restore src/AOM.FIPE.API.Tests/AOM.FIPE.API.Tests.csproj
    
    - name: Test
      run: dotnet test --no-build src/AOM.FIPE.API.Tests/AOM.FIPE.API.Tests.csproj --verbosity normal --logger "trx;LogFileName=test-results.trx"
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: AOM.FIPE.API Tests
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx
    
    - name: Publish
      if: github.event_name != 'pull_request'
      run: |
        dotnet publish --no-build src/AOM.FIPE.API/AOM.FIPE.API.csproj -o src/AOM.FIPE.API/publish

    - uses: actions/upload-artifact@v3
      if: github.event_name != 'pull_request'
      with:
        name: AOMFIPEAPI
        path: src/AOM.FIPE.API/publish